apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose-deploy.yml
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: certbot
  name: certbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: certbot
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose-deploy.yml
        kompose.version: 1.31.2 (a92241f79)
      labels:
        io.kompose.network/site-default: "true"
        io.kompose.service: certbot
    spec:
      containers:
      - name: certbot
        image: nylexdotnet/website:certbot
        env:
        - name: DOMAIN
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: DOMAIN
        - name: ACME_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: ACME_DEFAULT_EMAIL
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /vol/www
          name: certbot-web
        - mountPath: /etc/letsencrypt
          name: certbot-certs
      volumes:
      - name: certbot-web
        persistentVolumeClaim:
          claimName: certbot-web-pvc
      - name: certbot-certs
        persistentVolumeClaim:
          claimName: certbot-certs-pvc
