apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      # Init container
      # initContainers:
      # - name: init-dump-file
      #   image: alpine:3.14  # Lightweight image for basic operations
      #   command: ["/bin/sh", "-c", "echo 'Database dump data' > /mnt/volume/dump.dump"]
      #   volumeMounts:
      #   - name: dump-volume
      #     mountPath: /mnt/volume  # This is where the file will be created
      hostname: db-service
      containers:
      - name: db
        image: nylexdotnet/website:postgresql
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASS
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        # - name: dump-volume
        #   mountPath: /tmp/dump.dump
        #   subPath: dump.dump  # Mounts the file generated by the init container

      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      # - name: dump-volume
      #   persistentVolumeClaim:
      #     claimName: dump-pvc
