apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose-deploy.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nylex
  name: nylex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nylex
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose-deploy.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/site-default: "true"
        io.kompose.service: nylex
    spec:
      containers:
      - name: nylex
        image: nylexdotnet/website:latest
        env:
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: ALLOWED_HOSTS
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-url
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: DB_PASS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: SECRET_KEY
        resources: {}
        volumeMounts:
          - mountPath: /vol/web
            name: static-data
      restartPolicy: Always
      volumes:
        - name: static-data
          persistentVolumeClaim:
            claimName: static-data
status: {}
