apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ../docker-compose-deploy.yml
    kompose.version: 1.31.2 (a92241f79)
  labels:
    io.kompose.service: nylex
  name: nylex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nylex
  strategy:
    type: Recreate
  template:  # Add this line to define the Pod template
    metadata:
      labels:
        io.kompose.service: nylex
    spec:
      containers:
      - name: nylex
        image: nylexdotnet/website:latest
        env:
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: ALLOWED_HOSTS
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: db-url
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: DB_PASS
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: nylex-secret
              key: SECRET_KEY
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        volumeMounts:
        - mountPath: /vol/web
          name: static-data
      volumes:
      - name: static-data
        persistentVolumeClaim:
          claimName: static-pvc
