version: '3'
services:
  core:
    build:
      context: .
    command: >
      sh -c "cd core && \
      python manage.py runserver 0.0.0.0:80"
    ports:
      - "80:80"  # Expose Django on port 80
    volumes:
      - ./core:/core
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=django-insecure-m@7*pa2wxof8rk%rv3e9tf1tw#a$j!bpc+1b@95t=2zqlp99ym
      - DEBUG=1
      - ALLOWED_HOSTS=localhost ws-henry 127.0.0.1
      - HUDU_KEY=6gDhK1AHxG7opU62JFtw7q1h
      - RECAPTCHA_PUBLIC_KEY=6LfUqZsoAAAAAATRjLsKW0q4g56pSK79LxkQGMeV
      - RECAPTCHA_PRIVATE_KEY=6LfUqZsoAAAAAHc9v8xpHNVHUrZICnjLeH4T56n0
  # nginx:
  #   build: ./path/to-your-nginx-config
  #   ports:
  #     - "80:80"  # Expose Nginx on port 80
  # volumes:
  #   - ./path/to-your-static-files:/static  # Mount your static files