version: '3.8'

services:
  web:
    build:
      context: ./App
      dockerfile: Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:80
    volumes:
      - static_volume:/nylex/App/static
      - media_volume:/nylex/App/mediafiles
    expose:
      - 80
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/nylex/App/static
      - media_volume:/nylex/App/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: