# Generated by Django 4.2.4 on 2023-09-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_delete_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='alias',
        ),
    ]
