# Generated by Django 4.2.4 on 2023-09-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_title_page_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
