# Generated by Django 4.2.4 on 2023-09-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.SlugField(unique=True),
        ),
    ]
