# Generated by Django 4.2.4 on 2023-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_page_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='alias',
        ),
        migrations.AddField(
            model_name='page',
            name='banner',
            field=models.ImageField(default='/home/static/media/backrooms.JPG', upload_to=''),
            preserve_default=False,
        ),
    ]
