# Generated by Django 4.2.4 on 2023-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_page_alias_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.SlugField(max_length=200),
        ),
    ]
