# Generated by Django 4.2.4 on 2023-09-08 18:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_page_slug_alter_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
