# Generated by Django 4.2.4 on 2023-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_page_banner_alter_page_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='Nylex.net specializes in Enterprise Network Solutions and Communication Technologies.', max_length=500),
            preserve_default=False,
        ),
    ]
